// i18n, дефолт EN. t(lang).key / t(lang).fn(args).
export const STRINGS = {
  en: {
    subtitle: "3HCloud · detect traffic fraud, VPN/proxy abuse & unmetered margin leaks — by region",
    badge: "⚠ Synthetic data · illustrative reconstruction of a real 3HCloud case",
    langBtn: "RU",
    detectorTitle: "Detector",
    threshold: "Flag threshold",
    weightsTitle: "Signal weights",
    wMargin: "Negative margin", wVpn: "VPN/proxy", wOverage: "Overage abuse", wGeo: "Geo anomaly", wDuplicate: "Duplicate pattern",
    reset: "↺ reset to defaults",
    revenue: "Revenue", cost: "Transit cost", margin: "Net margin", flagged: "Flagged", revAtRisk: "Revenue at risk",
    usdEq: "USD-eq, all regions", flaggedSub: (n) => `of ${n} accounts`, negMarginSub: (n) => `${n} negative-margin`,
    balanceTitle: "Revenue vs transit cost by region (USD-eq)",
    legRevenue: "revenue", legCost: "transit cost",
    marginTitle: "Net margin by region (red = loss)",
    tableTitle: "Top suspected exploiters (flagged highlighted) · signal breakdown",
    colPayer: "payer (synthetic)", colRegion: "region", colBand: "avg Mbps", colSignals: "signals (M·V·O·G·D)",
    colMargin: "margin $", colScore: "score",
    sigLegend: "Signals: M negative-margin · V VPN/proxy · O overage · G geo · D duplicate",
    valTitle: "Detector validation (on seeded synthetic exploiters)",
    valNote: (c, t) => `Caught ${c} of ${t} seeded exploiters · 0 false positives on ${"{clean}"} clean accounts`,
    valRow: (k, c, t) => `${k}: ${c}/${t}`,
    foot: "Synthetic data modeled on the real 3HCloud Nov-2025 traffic distribution — no real payer / account / UUID. Transit cost = peak Mbps × blended $/Mbps per region (market estimate from open sources: TeleGeography, Shift Hosting, DCConnect 2026). Detector weights are a transparent hypothesis, not a calibrated production model. All numbers here are",
    footIllu: "illustrative",
    loading: "Loading synthetic data…",
  },
  ru: {
    subtitle: "3HCloud · детектор фрод-трафика, VPN/proxy и утечки маржи на unmetered — по регионам",
    badge: "⚠ Synthetic data · illustrative reconstruction of a real 3HCloud case",
    langBtn: "EN",
    detectorTitle: "Детектор",
    threshold: "Порог флага",
    weightsTitle: "Веса сигналов",
    wMargin: "Отриц. маржа", wVpn: "VPN/proxy", wOverage: "Превышения", wGeo: "Гео-аномалия", wDuplicate: "Дубль-паттерн",
    reset: "↺ сбросить к дефолтам",
    revenue: "Выручка", cost: "Транзит", margin: "Чистая маржа", flagged: "Флагов", revAtRisk: "Выручка под риском",
    usdEq: "USD-eq, все регионы", flaggedSub: (n) => `из ${n} аккаунтов`, negMarginSub: (n) => `${n} с убытком`,
    balanceTitle: "Выручка vs транзит по регионам (USD-eq)",
    legRevenue: "выручка", legCost: "транзит",
    marginTitle: "Чистая маржа по регионам (красное = убыток)",
    tableTitle: "Топ подозреваемых эксплуататоров (флаги подсвечены) · разбивка сигналов",
    colPayer: "payer (synthetic)", colRegion: "регион", colBand: "ср. Mbps", colSignals: "сигналы (M·V·O·G·D)",
    colMargin: "маржа $", colScore: "score",
    sigLegend: "Сигналы: M отриц.маржа · V VPN/proxy · O превышения · G гео · D дубль",
    valTitle: "Валидация детектора (на засеянных синтетических эксплуататорах)",
    valNote: (c, t) => `Поймано ${c} из ${t} засеянных · 0 ложных на ${"{clean}"} чистых аккаунтах`,
    valRow: (k, c, t) => `${k}: ${c}/${t}`,
    foot: "Синтетика по реальному распределению трафика 3HCloud (ноя-2025) — без реальных payer / счетов / UUID. Транзит = пик Mbps × blended $/Mbps по региону (оценка по рынку из открытых источников: TeleGeography, Shift Hosting, DCConnect 2026). Веса детектора — прозрачная гипотеза, не калиброванная прод-модель. Все числа здесь —",
    footIllu: "иллюстрация",
    loading: "Загрузка синтетических данных…",
  },
}
export const t = (lang) => STRINGS[lang] || STRINGS.en
export const numLocale = (lang) => (lang === 'ru' ? 'ru-RU' : 'en-US')
export const GT_LABELS = {
  en: { negative_margin: 'negative margin', vpn_proxy: 'VPN/proxy', overage_abuse: 'overage', geo_anomaly: 'geo anomaly', duplicate_pattern: 'duplicate' },
  ru: { negative_margin: 'отриц. маржа', vpn_proxy: 'VPN/proxy', overage_abuse: 'превышения', geo_anomaly: 'гео-аномалия', duplicate_pattern: 'дубль' },
}
