// i18n, дефолт EN. t(lang).key / t(lang).fn(args).
export const STRINGS = {
  en: {
    subtitle: "3HCloud · detect traffic fraud, VPN/proxy abuse & unmetered margin leaks — by region",
    badge: "⚠ Synthetic data · illustrative reconstruction of a real 3HCloud case",
    langBtn: "RU",
    detectorTitle: "Detector",
    threshold: "Flag threshold",
    weightsTitle: "Signal weights",
    wMargin: "Negative margin", wVpn: "VPN/proxy", wOverage: "Overage abuse", wGeo: "Geo anomaly", wDuplicate: "Duplicate pattern",
    reset: "↺ reset to defaults",
    revenue: "Revenue", cost: "Transit cost", margin: "Net margin", flagged: "Flagged", revAtRisk: "Revenue at risk",
    usdEq: "USD-eq, all regions", flaggedSub: (n) => `of ${n} accounts`, negMarginSub: (n) => `${n} negative-margin`,
    balanceTitle: "Revenue vs transit cost by region (USD-eq)",
    legRevenue: "revenue", legCost: "transit cost",
    marginTitle: "Net margin by region (red = loss)",
    tableTitle: "Top suspected exploiters (flagged highlighted) · signal breakdown",
    colPayer: "payer (synthetic)", colRegion: "region", colBand: "avg Mbps", colSignals: "signals (M·V·O·G·D)",
    colMargin: "margin $", colScore: "score",
    sigLegend: "Signals: M negative-margin · V VPN/proxy · O overage · G geo · D duplicate",
    valTitle: "Detector validation (on seeded synthetic exploiters)",
    valNote: (c, t) => `Caught ${c} of ${t} seeded exploiters · 0 false positives on ${"{clean}"} clean accounts`,
    valRow: (k, c, t) => `${k}: ${c}/${t}`,
    foot: "Synthetic data modeled on the real 3HCloud Nov-2025 traffic distribution — no real payer / account / UUID. Transit cost = peak Mbps × blended $/Mbps per region (market estimate from open sources: TeleGeography, Shift Hosting, DCConnect 2026). Detector weights are a transparent hypothesis, not a calibrated production model. All numbers here are",
    footIllu: "illustrative",
    loading: "Loading synthetic data…",
    tabDetector: "Detector", tabTariff: "Tariff what-if",
    help: {
      threshold: "Score above which an account is flagged as a suspected exploiter. Lower = catch more (higher recall) but more false positives.",
      margin: "Transit cost eats a large share of the account's revenue (negative-margin). Core of unmetered economics.",
      vpn: "Thin VM + fat pipe: low compute-per-Mbps, symmetric out/in (~1.0), 24/7 duty cycle — classic VPN/proxy reselling.",
      overage: "Sustained bandwidth above the committed port + accrued overage hours.",
      geo: "Bandwidth many times above the region median — a traffic outlier.",
      duplicate: "Near-identical traffic fingerprint across several accounts under one beneficiary, each kept just under committed to dodge overage (95th-percentile evasion).",
      flatMult: "Multiplier on the Flat-rate Unmetered monthly port price (3HCloud reference tariff). >1 = raise flat prices, <1 = discount. Watch how it changes DC margin per region.",
      elasticMult: "Multiplier on the Elastic overage rate ($/Mbps-hour above the 10 Mb/s base). Higher = charge heavy users more; affects only accounts exceeding 10 Mb/s.",
      blendedMult: "Multiplier on the blended $/Mbps transit cost (your cost side). >1 models more expensive channels; shows sensitivity of margin to transit price.",
    },
    tfTitle: "Unmetered tariff what-if",
    tfPatterns: "Compares current plan vs two Unmetered billing patterns: (A) Flat-rate unmetered — fixed monthly per port; (B) Elastic — 10 Mb/s base included, billed hourly per Mbps above. Reference tariffs are 3HCloud's real price list (MSK estimated). Vary them and watch unit & DC economics.",
    tfFlatMult: "Flat-rate tariff ×", tfElasticMult: "Elastic (overage) tariff ×", tfBlendedMult: "Transit cost ×",
    kCurrent: "Current margin", kFlat: "Flat-unmetered margin", kElastic: "Elastic margin",
    tfChartTitle: "Net margin by region · current vs flat vs elastic (USD-eq)",
    tfTableTitle: "Per-region economics under each pattern",
    colRegion2: "region", colCur: "current $", colFlat: "flat $", colElastic: "elastic $", colCost2: "transit $",
    legCur: "current", legFlat: "flat-unmetered", legElastic: "elastic 10Mb+overage",
    tfNote: "Flat captures revenue from light users (port fee for everyone); Elastic charges only heavy users above 10 Mb/s — light users pay ~0 bandwidth. The right pattern depends on your traffic mix per region.",
  },
  ru: {
    subtitle: "3HCloud · детектор фрод-трафика, VPN/proxy и утечки маржи на unmetered — по регионам",
    badge: "⚠ Synthetic data · illustrative reconstruction of a real 3HCloud case",
    langBtn: "EN",
    detectorTitle: "Детектор",
    threshold: "Порог флага",
    weightsTitle: "Веса сигналов",
    wMargin: "Отриц. маржа", wVpn: "VPN/proxy", wOverage: "Превышения", wGeo: "Гео-аномалия", wDuplicate: "Дубль-паттерн",
    reset: "↺ сбросить к дефолтам",
    revenue: "Выручка", cost: "Транзит", margin: "Чистая маржа", flagged: "Флагов", revAtRisk: "Выручка под риском",
    usdEq: "USD-eq, все регионы", flaggedSub: (n) => `из ${n} аккаунтов`, negMarginSub: (n) => `${n} с убытком`,
    balanceTitle: "Выручка vs транзит по регионам (USD-eq)",
    legRevenue: "выручка", legCost: "транзит",
    marginTitle: "Чистая маржа по регионам (красное = убыток)",
    tableTitle: "Топ подозреваемых эксплуататоров (флаги подсвечены) · разбивка сигналов",
    colPayer: "payer (synthetic)", colRegion: "регион", colBand: "ср. Mbps", colSignals: "сигналы (M·V·O·G·D)",
    colMargin: "маржа $", colScore: "score",
    sigLegend: "Сигналы: M отриц.маржа · V VPN/proxy · O превышения · G гео · D дубль",
    valTitle: "Валидация детектора (на засеянных синтетических эксплуататорах)",
    valNote: (c, t) => `Поймано ${c} из ${t} засеянных · 0 ложных на ${"{clean}"} чистых аккаунтах`,
    valRow: (k, c, t) => `${k}: ${c}/${t}`,
    foot: "Синтетика по реальному распределению трафика 3HCloud (ноя-2025) — без реальных payer / счетов / UUID. Транзит = пик Mbps × blended $/Mbps по региону (оценка по рынку из открытых источников: TeleGeography, Shift Hosting, DCConnect 2026). Веса детектора — прозрачная гипотеза, не калиброванная прод-модель. Все числа здесь —",
    footIllu: "иллюстрация",
    loading: "Загрузка синтетических данных…",
    tabDetector: "Детектор", tabTariff: "Тарифы (what-if)",
    help: {
      threshold: "Порог score, выше которого аккаунт помечается подозреваемым эксплуататором. Ниже = ловим больше (выше recall), но больше ложных срабатываний.",
      margin: "Стоимость транзита съедает большую долю выручки аккаунта (отрицательная маржа). Ядро unmetered-экономики.",
      vpn: "Тонкая ВМ + толстая труба: мало compute на Mbps, симметрия out/in (~1.0), круглосуточно — классическая перепродажа VPN/proxy.",
      overage: "Устойчивая полоса выше committed-порта + накопленные часы превышения.",
      geo: "Полоса кратно выше медианы региона — трафик-выброс.",
      duplicate: "Почти одинаковый фингерпринт трафика у нескольких аккаунтов под одним бенефициаром, каждый держится чуть ниже committed, чтобы обойти превышение (обход 95-го перцентиля).",
      flatMult: "Множитель месячной цены Flat-rate Unmetered за порт (опорный тариф 3HCloud). >1 — поднять цены, <1 — скидка. Смотри, как меняется маржа ЦОД по регионам.",
      elasticMult: "Множитель ставки Elastic за превышение ($/Mbps-час сверх базовых 10 Mb/s). Выше = дороже для тяжёлых; влияет только на аккаунты выше 10 Mb/s.",
      blendedMult: "Множитель blended $/Mbps стоимости транзита (расходная сторона). >1 — моделирует дорогие каналы; показывает чувствительность маржи к цене транзита.",
    },
    tfTitle: "What-if по Unmetered-тарифам",
    tfPatterns: "Сравнивает текущий план с двумя паттернами Unmetered: (A) Flat-rate — фикс в месяц за порт; (B) Elastic — 10 Mb/s включено, выше — почасово за Mbps. Опорные тарифы — реальный прайс 3HCloud (MSK — оценка). Варьируй их и смотри на юнит- и ЦОД-экономику.",
    tfFlatMult: "Тариф Flat-rate ×", tfElasticMult: "Тариф Elastic (превышение) ×", tfBlendedMult: "Стоимость транзита ×",
    kCurrent: "Маржа сейчас", kFlat: "Маржа Flat-unmetered", kElastic: "Маржа Elastic",
    tfChartTitle: "Чистая маржа по регионам · сейчас vs flat vs elastic (USD-eq)",
    tfTableTitle: "Экономика по регионам в каждом паттерне",
    colRegion2: "регион", colCur: "сейчас $", colFlat: "flat $", colElastic: "elastic $", colCost2: "транзит $",
    legCur: "сейчас", legFlat: "flat-unmetered", legElastic: "elastic 10Mb+превыш.",
    tfNote: "Flat снимает выручку с лёгких пользователей (порт-плата со всех); Elastic берёт только с тяжёлых выше 10 Mb/s — лёгкие платят ~0 за полосу. Правильный паттерн зависит от микса трафика в регионе.",
  },
}
export const t = (lang) => STRINGS[lang] || STRINGS.en
export const numLocale = (lang) => (lang === 'ru' ? 'ru-RU' : 'en-US')
export const GT_LABELS = {
  en: { negative_margin: 'negative margin', vpn_proxy: 'VPN/proxy', overage_abuse: 'overage', geo_anomaly: 'geo anomaly', duplicate_pattern: 'duplicate' },
  ru: { negative_margin: 'отриц. маржа', vpn_proxy: 'VPN/proxy', overage_abuse: 'превышения', geo_anomaly: 'гео-аномалия', duplicate_pattern: 'дубль' },
}
